---
title: "Beyond Reconstruction: What Leads to Satisfaction in Post-Disaster Recovery?"

output: html_document

knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

### Abstract
> Many studies have shown that economic and political freedom better predict overall subjective satisfaction than income or material consumption. However, in the context of post-disaster reconstruction, whether freedom of choice in reconstruction is a better predictor of satisfaction than the extent of material reconstruction is much less clear. In this paper, employing ordinal logistic regression analysis to data collected in the aftermath of Nepal’s 7.8 Mw 2015 earthquake, we find that freedom of choice in the reconstruction process predicts households’ post-disaster subjective satisfaction better than the extent of physical reconstruction per se. Interestingly, many seemingly important predictors such as income, education, location, occupation, household size and age of respondents that we investigated are not statistically significant. Apart from freedom of choice, only gender and ethnicity are significant in explaining satisfaction with newly reconstructed houses. We also find a negative correlation between satisfaction level and inequality in such levels among ethnic groups; the reverse is true in the case of gender. These findings underscore the importance of freedom, and ethnic or gender-specific policies, in promoting well-being in post-disaster recovery.

<br/><br/>